"""add accomplishments weather anand mood fields to JournalEntry

Revision ID: c07d2af668dc
Revises: eefbb6d2fc3d
Create Date: 2025-01-02 21:42:37.320878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07d2af668dc'
down_revision = 'eefbb6d2fc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accomplishments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('mood')
        batch_op.drop_column('weather')
        batch_op.drop_column('accomplishments')

    # ### end Alembic commands ###
